#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOST="$ROOT/third_party/quiche-0.29.3"
PATCH_DIR="$ROOT/patches/p2"
EXPECTED_SHA="55886df3be579579207104c8e645825b6347a209"

usage() {
  cat <<'EOF'
Usage:
  tools/p2/patch-dev.sh prepare
  tools/p2/patch-dev.sh export <NNNN-name.patch>
  tools/p2/patch-dev.sh reset

prepare:
  Reset the frozen host, apply the current P2 patch stack, and stage that stack
  as the development baseline. Edit Rust source files after this step.

export:
  Export only the unstaged source edits (relative to the staged P2 baseline)
  as a git-generated patch in patches/p2/. The patch format/hunk counts are
  generated by git, never handwritten.

reset:
  Return the frozen host worktree to the pinned SHA and remove untracked files.
EOF
}

check_sha() {
  local actual
  actual="$(git -C "$HOST" rev-parse HEAD)"
  if [[ "$actual" != "$EXPECTED_SHA" ]]; then
    echo "Expected frozen host $EXPECTED_SHA, got $actual" >&2
    exit 2
  fi
}

reset_host() {
  git -C "$HOST" reset --hard "$EXPECTED_SHA"
  git -C "$HOST" clean -fd
}

case "${1:-}" in
  prepare)
    check_sha
    if ! git -C "$HOST" diff --quiet || ! git -C "$HOST" diff --cached --quiet; then
      echo "Host worktree is dirty. Use 'patch-dev.sh reset' first." >&2
      exit 3
    fi

    bash "$ROOT/tools/p2/apply-host-patches.sh"
    git -C "$HOST" add -A

    echo
    echo "P2 patch stack is staged as the baseline."
    echo "Edit source files directly under: $HOST"
    echo "Then export with: tools/p2/patch-dev.sh export NNNN-name.patch"
    ;;

  export)
    name="${2:-}"
    if [[ -z "$name" || "$name" != *.patch || "$name" == */* ]]; then
      echo "export requires a simple *.patch filename, e.g. 0010-hotpath.patch" >&2
      exit 4
    fi

    check_sha
    if git -C "$HOST" diff --cached --quiet; then
      echo "No staged P2 baseline found. Run 'patch-dev.sh prepare' first." >&2
      exit 5
    fi
    if git -C "$HOST" diff --quiet; then
      echo "No unstaged source edits to export." >&2
      exit 6
    fi

    git -C "$HOST" diff --check
    out="$PATCH_DIR/$name"
    git -C "$HOST" diff --binary --full-index --no-ext-diff > "$out"

    if [[ ! -s "$out" ]]; then
      echo "Generated patch is empty: $out" >&2
      exit 7
    fi

    echo "Generated: $out"
    echo "Run tools/p2/preflight.sh before committing."
    ;;

  reset)
    check_sha
    reset_host
    echo "Frozen host reset to $EXPECTED_SHA"
    ;;

  *)
    usage
    exit 1
    ;;
esac
